version: "1"
services:

  client:
    build: client
    ports:
      - "5000:3000"
    volumes:
      - ./client/src:/app/client/src
    container_name: test-bd-manga_website-client
    command: ["npm", "run", "test-bd"]
    depends_on:
      - server

  server:
    build: server
    ports:
      - "8000:5000"
    volumes:
      - ./server/src:/app/server/src
    container_name: test-bd-manga_website-server
    command: ["npm", "run", "test-bd"]