version: "1"
services:

  server:
    build: server
    ports:
      - "8000:5000"
    volumes:
      - ./server/src:/app/server/src
    container_name: test-manga_website-server
    command: ["npm", "run", "test-controllers"]