version: "1"
services:

  #  Добавить возможность выгружать файлы из docker контейнера

  client:
    build: client
    ports:
      - "4000:3000"
    volumes:
      - ./client/src:/app/client/src
    container_name: manga_website-client-dev
    command: ["npm", "run", "dev"]
    depends_on:
      - server

  server:
    build: server
    ports:
      - "6000:5000"
    volumes:
      - ./server/src:/app/server/src
    container_name: manga_website-server-dev
    command: ["npm", "run", "dev"]