version: "1"
services:

  client:
    build: client
    ports:
      - "4000:3000"
    volumes:
      - ./client/src:/app/client/src
    container_name: dev-manga_website-client
    command: ["npm", "run", "dev"]
    depends_on:
      - server

  server:
    build: server
    ports:
      - "7000:5000"
    volumes:
      - ./server/src:/app/server/src
    container_name: dev-manga_website-server
    command: ["npm", "run", "dev"]